Fix/#88table arrange
SymbaX/symbax pull request #144
Opened 2023-07-06 06:12 UTC by daiwasan

## 対応したISSUE
- close #ISSUE_NUMBER

## 概要
-新しくマイグレーションファイルを作ったlocalで表示できるか
確認し忘れてます

## リンク
-

## レビュー箇所
-[ ] 17行のdetail
-[ ] 21行のextarnal_link

## スクリーンショット
Before | After
:--: | :--:
<img src="" width="300" /> | <img src="" width="300" />

2023-07-06 06:16 UTC, ENDOTAKUMI commented
```sh

endotakumi@endoutauminombp symbax % ./vendor/bin/sail php artisan migrate

   INFO  Preparing database.  

  Creating migration table ............................................................................................................... 42ms DONE

   INFO  Running migrations.  

  2014_10_12_000000_create_users_table ................................................................................................... 43ms DONE
  2014_10_12_100000_create_password_reset_tokens_table ................................................................................... 45ms DONE
  2019_08_19_000000_create_failed_jobs_table ............................................................................................. 39ms DONE
  2019_12_14_000001_create_personal_access_tokens_table .................................................................................. 46ms DONE
  2023_06_14_142057_create_colleges_table ................................................................................................ 51ms DONE
  2023_06_14_150249_create_departments_table ............................................................................................. 88ms DONE
  2023_06_17_220027_add_college_and_department_to_users ................................................................................. 109ms DONE
  2023_06_20_132847_create_events_table ................................................................................................... 7ms FAIL

   Illuminate\Database\QueryException 

  SQLSTATE[42000]: Syntax error or access violation: 1166 Incorrect column name '' (Connection: mysql, SQL: create table `events` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `detail` varchar(1000) not null, `category` varchar(255) not null, `tag` varchar(255) not null, `conditions_of_participation` varchar(255) not null, `estarnal_link` varchar(255) not null, `datetime` datetime not null, `place` varchar(255) not null, `number_of_people` int not null, `product_image` varchar(255) not null, `creator_id` bigint unsigned not null, `` datetime not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:795
    791▕         // If an exception occurs when attempting to run a query, we'll format the error
    792▕         // message to include the bindings with SQL, which will make this exception a
    793▕         // lot more helpful to the developer instead of just the database's errors.
    794▕         catch (Exception $e) {
  ➜ 795▕             throw new QueryException(
    796▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    797▕             );
    798▕         }
    799▕     }

      +9 vendor frames 

  10  database/migrations/2023_06_20_132847_create_events_table.php:14
      Illuminate\Support\Facades\Facade::__callStatic()
      +24 vendor frames 

  35  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()

endotakumi@endoutauminombp symbax % 
```

2023-07-06 06:16 UTC, ENDOTAKUMI requested changes
migrateでエラー出た

2023-07-06 06:26 UTC, ENDOTAKUMI requested changes

2023-07-06 06:26 UTC, ENDOTAKUMI commented on resources/views/components/modal.blade.php
このファイルインデント結構変わってるな...
明日拡張機能入れるか...

2023-07-06 06:26 UTC, ENDOTAKUMI commented on database/migrations/2023_07_05_152210_create_event_table.php
> +        Schema::create('event', function (Blueprint $table) {
新規でファイル作ってるけどなんでだろ。。

2023-07-06 06:26 UTC, ENDOTAKUMI commented on database/migrations/2023_06_20_132847_create_events_table.php
> +            $table->datetime('');
カラムの名前が指定されていないため

2023-07-06 06:35 UTC, daiwasan commented
> ```shell
> endotakumi@endoutauminombp symbax % ./vendor/bin/sail php artisan migrate
> 
>    INFO  Preparing database.  
> 
>   Creating migration table ............................................................................................................... 42ms DONE
> 
>    INFO  Running migrations.  
> 
>   2014_10_12_000000_create_users_table ................................................................................................... 43ms DONE
>   2014_10_12_100000_create_password_reset_tokens_table ................................................................................... 45ms DONE
>   2019_08_19_000000_create_failed_jobs_table ............................................................................................. 39ms DONE
>   2019_12_14_000001_create_personal_access_tokens_table .................................................................................. 46ms DONE
>   2023_06_14_142057_create_colleges_table ................................................................................................ 51ms DONE
>   2023_06_14_150249_create_departments_table ............................................................................................. 88ms DONE
>   2023_06_17_220027_add_college_and_department_to_users ................................................................................. 109ms DONE
>   2023_06_20_132847_create_events_table ................................................................................................... 7ms FAIL
> 
>    Illuminate\Database\QueryException 
> 
>   SQLSTATE[42000]: Syntax error or access violation: 1166 Incorrect column name '' (Connection: mysql, SQL: create table `events` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `detail` varchar(1000) not null, `category` varchar(255) not null, `tag` varchar(255) not null, `conditions_of_participation` varchar(255) not null, `estarnal_link` varchar(255) not null, `datetime` datetime not null, `place` varchar(255) not null, `number_of_people` int not null, `product_image` varchar(255) not null, `creator_id` bigint unsigned not null, `` datetime not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')
> 
>   at vendor/laravel/framework/src/Illuminate/Database/Connection.php:795
>     791▕         // If an exception occurs when attempting to run a query, we'll format the error
>     792▕         // message to include the bindings with SQL, which will make this exception a
>     793▕         // lot more helpful to the developer instead of just the database's errors.
>     794▕         catch (Exception $e) {
>   ➜ 795▕             throw new QueryException(
>     796▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
>     797▕             );
>     798▕         }
>     799▕     }
> 
>       +9 vendor frames 
> 
>   10  database/migrations/2023_06_20_132847_create_events_table.php:14
>       Illuminate\Support\Facades\Facade::__callStatic()
>       +24 vendor frames 
> 
>   35  artisan:35
>       Illuminate\Foundation\Console\Kernel::handle()
> 
> endotakumi@endoutauminombp symbax % 
> ```

あれマイグレーションファイル/home/daiwa/symbax/database/migrations/2023_07_05_152210_create_event_table.php作ったけどpushされてないぽいね

2023-07-06 06:36 UTC, daiwasan commented on database/migrations/2023_07_05_152210_create_event_table.php
> +        Schema::create('event', function (Blueprint $table) {
つくった、、、過去のやつ編集した方がいい？

2023-07-06 06:37 UTC, daiwasan commented on database/migrations/2023_06_20_132847_create_events_table.php
> +            $table->datetime('');
06_20のマイグレーションファイルに加えます((+_+))

2023-07-06 06:39 UTC, ENDOTAKUMI commented on database/migrations/2023_07_05_152210_create_event_table.php
> +        Schema::create('event', function (Blueprint $table) {
んー新規ファイルで作るのは正解なんだけど
　このテーブルに項目を追加するとか
　このテーブルのこの型を変更する
みたいな書き方が正しかった気がする…
（多分調べれば出る）

それかAWSのDBも全部消すんだったら直接過去のやつ編集でもいいけどw

2023-07-06 06:42 UTC, daiwasan commented on database/migrations/2023_07_05_152210_create_event_table.php
> +        Schema::create('event', function (Blueprint $table) {
> んー新規ファイルで作るのは正解なんだけど
> 　このテーブルに項目を追加するとか
> 　このテーブルのこの型を変更する
> みたいな書き方が正しかった気がする…

あぁ～あったな
なんかえんたくが前どっかにリンク張ってくれてたよね探してみる

2023-07-06 06:44 UTC, daiwasan commented on database/migrations/2023_07_05_152210_create_event_table.php
> +        Schema::create('event', function (Blueprint $table) {
https://github.com/SymbaX/symbax/issues/14#issuecomment-1588538488これやな

2023-07-08 03:46 UTC, ENDOTAKUMI commented
一旦 #157 で対応したので閉じます....
まだ変更できそうなところありそうだからそっちお願いしたい..

2023-07-08 03:46 UTC, closed without merging