エラーページを作成
SymbaX/symbax pull request #33
Opened 2023-06-14 06:33 UTC by MACHIDAMinoru

## 対応したISSUE
- close #31 

## 概要
-

## リンク
-

## レビュー箇所
- [ ] レビューしてほしい箇所

## スクリーンショット
Before | After
:--: | :--:
<img src="" width="300" /> | <img src="" width="300" />

2023-06-14 06:35 UTC, ENDOTAKUMI commented
developブランチにプルリクして

2023-06-14 06:39 UTC, ENDOTAKUMI requested changes
👍　
これ上下中央にならないー？

2023-06-14 06:46 UTC, ENDOTAKUMI commented
@MACHIDAMinoru 
issueに書いたの俺が思いついたやつしか書かなかったけど
500とか他のエラーも作れる？

2023-06-14 06:47 UTC, MACHIDAMinoru commented
@ENDOTAKUMI 
おけ
もろもろ編集するー！

2023-06-15 03:58 UTC, ENDOTAKUMI commented on resources/views/errors/layouts/base.blade.php
> +<div class="error-wrap">
インデントずれてる...？

ショートカットキーを使う場合:
(Windows) `Shift `+ `Alt `+ `F`
(macOS) `Shift `+ `Option `+ `F`

2023-06-15 04:41 UTC, ENDOTAKUMI approved these changes
👍
一旦これで

2023-06-15 04:41 UTC, merged